// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadHttp_trace returns the embedded CollectionSpec for http_trace.
func loadHttp_trace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Http_traceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load http_trace: %w", err)
	}

	return spec, err
}

// loadHttp_traceObjects loads http_trace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*http_traceObjects
//	*http_tracePrograms
//	*http_traceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadHttp_traceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadHttp_trace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// http_traceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type http_traceSpecs struct {
	http_traceProgramSpecs
	http_traceMapSpecs
	http_traceVariableSpecs
}

// http_traceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type http_traceProgramSpecs struct {
	TraceHttpWrite *ebpf.ProgramSpec `ebpf:"trace_http_write"`
}

// http_traceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type http_traceMapSpecs struct {
	Events  *ebpf.MapSpec `ebpf:"events"`
	Scratch *ebpf.MapSpec `ebpf:"scratch"`
}

// http_traceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type http_traceVariableSpecs struct {
}

// http_traceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadHttp_traceObjects or ebpf.CollectionSpec.LoadAndAssign.
type http_traceObjects struct {
	http_tracePrograms
	http_traceMaps
	http_traceVariables
}

func (o *http_traceObjects) Close() error {
	return _Http_traceClose(
		&o.http_tracePrograms,
		&o.http_traceMaps,
	)
}

// http_traceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadHttp_traceObjects or ebpf.CollectionSpec.LoadAndAssign.
type http_traceMaps struct {
	Events  *ebpf.Map `ebpf:"events"`
	Scratch *ebpf.Map `ebpf:"scratch"`
}

func (m *http_traceMaps) Close() error {
	return _Http_traceClose(
		m.Events,
		m.Scratch,
	)
}

// http_traceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadHttp_traceObjects or ebpf.CollectionSpec.LoadAndAssign.
type http_traceVariables struct {
}

// http_tracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadHttp_traceObjects or ebpf.CollectionSpec.LoadAndAssign.
type http_tracePrograms struct {
	TraceHttpWrite *ebpf.Program `ebpf:"trace_http_write"`
}

func (p *http_tracePrograms) Close() error {
	return _Http_traceClose(
		p.TraceHttpWrite,
	)
}

func _Http_traceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed http_trace_bpfeb.o
var _Http_traceBytes []byte
